datadog:
  apiKey: replaceme
  remoteConfiguration:
    enabled: true
  apm:
    portEnabled: true
    instrumentation:
      enabled: true                 
      targets:
        - name: "default-target"
          namespaceSelector:
            matchNames:
              - "default"
          ddTraceVersions:
            java: "1"
            python: "3"
            js: "5"
            php: "1"
            dotnet: "3"
  logs:
    enabled: true
    containerCollectAll: true
  logLevel: debug
  env:
    - name: DD_ENV
      value: demo
  otlp:
    receiver:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
          enabled: true
  orchestratorExplorer:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true   
  kubelet:
    useApiServer: true
  asm:
    threats:
      enabled: true
  cws:
    enabled: true
  cspm:
    enabled: true
  sbom:
    enabled: true
    containerImage:
      enabled: true
    host:
      enabled: true
agents:
  image:
    tag: 7.66.0
  containers:
    agent:
      # resources for the Agent container
      resources:
        requests:
          cpu: 200m
          memory: 256Mi

    traceAgent:
      # resources for the Trace Agent container
      resources:
        requests:
          cpu: 100m
          memory: 200Mi

    processAgent:
      # resources for the Process Agent container
      resources:
        requests:
          cpu: 100m
          memory: 200Mi

  priorityClassCreate: true

providers:
  gke:
    autopilot: true

clusterAgent:
  image:
    tag: 7.66.0
  admissionController:
    configMode: hostip
    mutateUnlabelled: true


