datadog:
  apiKey: replaceme
  remoteConfiguration:
    enabled: true
  apm:
    portEnabled: true
    instrumentation:
      enabled: true                 
      targets:
        - name: "default-target"
          podSelector:
              matchExpressions:
                - key: app
                  operator: NotIn
                  values:
                  - adservice
          ddTraceVersions:
            java: "1"
            python: "3"
            js: "5"
            php: "1"
            dotnet: "3"
  logs:
    enabled: true
    containerCollectAll: true
  # logLevel: debug
  env:
    - name: DD_ENV
      value: demo
  otlp:
    receiver:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
          enabled: true
  orchestratorExplorer:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true   
  kubelet:
    useApiServer: true
  kubeStateMetricsCore:
    enabled: true
  asm:
    threats:
      enabled: true
  cws:
    enabled: true
  cspm:
    enabled: true
  securityAgent:
    # Enables Threat Detection
    runtime:
      enabled: true
    # Enables Misconfigurations
    compliance:
      enabled: true
      host_benchmarks:
        enabled: true
  sbom:
    enabled: true
    containerImage:
      enabled: true
      uncompressedLayersSupport: true
    host:
      enabled: true
agents:
  image:
    tag: 7.66.0

clusterAgent:
  image:
    tag: 7.66.0
  admissionController:
    configMode: socket
    mutateUnlabelled: true


