# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# resources:
#   - otel-collector.yaml
patches:
# adservice - Use Datadog Single Step APM
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: adservice
      labels:
        app: adservice
    spec:
      selector:
        matchLabels:
          app: adservice
      template:
        metadata:
          labels:
            app: adservice
            tags.datadoghq.com/env: "demo" # Unified service tag - Pod Env tag
            tags.datadoghq.com/service: "adservice" # Unified service tag - Pod Service tag
            tags.datadoghq.com/version: "0.10.1" # Unified service tag - Pod Version tag
            admission.datadoghq.com/enabled: "true" # Enable Admission Controller to mutate new pods in this deployment
          annotations:
            admission.datadoghq.com/java-lib.version: "1.42.2"
        spec:
          containers:
          - name: server
            image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.1
            volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            readinessProbe:
              initialDelaySeconds: 60
              periodSeconds: 20
              grpc:
                port: 9555
            livenessProbe:
              initialDelaySeconds: 60
              periodSeconds: 20
              grpc:
                port: 9555
          volumes:
          - name: tmp-volume
            emptyDir: {}
# cartservice - Use Datadog Single Step APM
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cartservice
      labels:
        app: cartservice
    spec:
      selector:
        matchLabels:
          app: cartservice
      template:
        metadata:
          labels:
            app: cartservice
            tags.datadoghq.com/env: "demo" # Unified service tag - Pod Env tag
            tags.datadoghq.com/service: "cartservice" # Unified service tag - Pod Service tag
            tags.datadoghq.com/version: "0.10.1" # Unified service tag - Pod Version tag
            admission.datadoghq.com/enabled: "true" # Enable Admission Controller to mutate new pods in this deployment
          annotations:
            admission.datadoghq.com/dotnet-lib.version: "3.5.0"
# checkoutservice - tracing, profiler
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: checkoutservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: COLLECTOR_SERVICE_ADDR
                value: "$(HOST_IP):4317"
              - name: OTEL_SERVICE_NAME
                value: "checkoutservice"
              - name: ENABLE_TRACING
                value: "1"
              - name: ENABLE_PROFILER
                value: "1"
# currencyservice - tracing, profiler
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: currencyservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: COLLECTOR_SERVICE_ADDR
                value: "$(HOST_IP):4317"
              - name: OTEL_SERVICE_NAME
                value: "currencyservice"
              - name: ENABLE_TRACING
                value: "1"
              - name: DISABLE_PROFILER
                $patch: delete
# emailservice - tracing, profiler
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: emailservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: COLLECTOR_SERVICE_ADDR
                value: "$(HOST_IP):4317"
              - name: OTEL_SERVICE_NAME
                value: "emailservice"
              - name: ENABLE_TRACING
                value: "1"
              - name: DISABLE_PROFILER
                $patch: delete
# frontend - tracing, profiler
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: ENABLE_TRACING
                value: "1"
              - name: COLLECTOR_SERVICE_ADDR
                value: "$(HOST_IP):4317"
              - name: OTEL_SERVICE_NAME
                value: "frontend"
              - name: ENABLE_PROFILER
                value: "1"
# paymentservice - tracing, profiler
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: paymentservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: COLLECTOR_SERVICE_ADDR
                value: "$(HOST_IP):4317"
              - name: OTEL_SERVICE_NAME
                value: "paymentservice"
              - name: ENABLE_TRACING
                value: "1"
              - name: DISABLE_PROFILER
                $patch: delete
# productcatalogservice - tracing, profiler
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: productcatalogservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: COLLECTOR_SERVICE_ADDR
                value: "$(HOST_IP):4317"
              - name: OTEL_SERVICE_NAME
                value: "productcatalogservice"
              - name: ENABLE_TRACING
                value: "1"
              - name: DISABLE_PROFILER
                value: "1"
# recommendationservice - tracing, profiler
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: recommendationservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: COLLECTOR_SERVICE_ADDR
                value: "$(HOST_IP):4317"
              - name: OTEL_SERVICE_NAME
                value: "recommendationservice"
              - name: ENABLE_TRACING
                value: "1"
              - name: DISABLE_PROFILER
                $patch: delete
# shippingservice - stats, tracing, profiler
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: shippingservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: DISABLE_PROFILER
                $patch: delete
helmCharts:
- name: datadog
  repo: https://helm.datadoghq.com
  releaseName: datadog-agent
  version: 3.80.0
  valuesInline:
    datadog:
      apiKey: replaceme
      apm:
        portEnabled: true
      logs:
        enabled: true
        containerCollectAll: true
      env:
        - name: DD_ENV
          value: demo
      otlp:
        receiver:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
              enabled: true
    agents:
      containers:
        agent:
          # resources for the Agent container
          resources:
            requests:
              cpu: 200m
              memory: 256Mi

        traceAgent:
          # resources for the Trace Agent container
          resources:
            requests:
              cpu: 100m
              memory: 200Mi

        processAgent:
          # resources for the Process Agent container
          resources:
            requests:
              cpu: 100m
              memory: 200Mi

      priorityClassCreate: true

    providers:
      gke:
        autopilot: true

    clusterAgent:
      admissionController:
        configMode: hostip